steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/exercise6cc-leon', '.']
    dir: 'backend'
    secretEnv: ['ENV_BE_NOTES']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/exercise6cc-leon']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'exercise6cc-leon',
        '--image',
        'gcr.io/$PROJECT_ID/exercise6cc-leon',
        '--timeout',
        '1000s',
        '--port',
        '5000',
        '--region',
        'us-central1',
        '--allow-unauthenticated'
      ]

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud beta run services add-iam-policy-binding exercise6cc-leon \
          --member="allUsers" \
          --role="roles/run.invoker" \
          --region=us-central1

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/env-be-notes/versions/latest
      env: ENV_BE_NOTES

options:
  logging: CLOUD_LOGGING_ONLY
