steps:
  # STEP 0: Copy .env dari bucket ke backend
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "gs://kelompok_09_e/.env", "./backend/.env"]

  # STEP 1: Build Docker image (jika kamu pakai Dockerfile)
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/exercise6cc-leon", "."]
    dir: "backend"

  # STEP 2: Push ke Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/exercise6cc-leon"]

  # STEP 3: Deploy ke Cloud Run TANPA `--set-env-vars`
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "exercise6cc-leon",
        "--image", "gcr.io/$PROJECT_ID/exercise6cc-leon",
        "--region", "us-central1",
        "--port", "5000",
        "--allow-unauthenticated",
        "--timeout", "1000s",
        "--update-env-vars", "NODE_ENV=production"
      ]

options:
  logging: CLOUD_LOGGING_ONLY
