### Register User Baru
POST http://localhost:5000/register
Content-Type: application/json

{
  "username": "leon",
  "password": "password123",
  "confPassword": "password123"
}

### Login User
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "leon",
  "password": "password123"
}

### Get Users (Notes) - Butuh Token dari Response Login
# Ganti ACCESS_TOKEN_VALUE dengan token yang didapat dari response login
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJuYW1lIjoibGVvbiIsImlhdCI6MTc0ODA3NDc3MSwiZXhwIjoxNzQ4MDc4MzcxfQ.TfuogRoC7g-LFBNwuxBxiaPAsAp9RXzgrpxspl8vDbw

### Add Note - Butuh Token
POST http://localhost:5000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJuYW1lIjoibGVvbiIsImlhdCI6MTc0ODA3NDc3MSwiZXhwIjoxNzQ4MDc4MzcxfQ.TfuogRoC7g-LFBNwuxBxiaPAsAp9RXzgrpxspl8vDbw

{
  "name": "Belajar Cloud Computing",
  "title": "Catatan Penting",
  "isi_notes": "Ini adalah catatan untuk belajar cloud computing."
}

###
POST http://localhost:5000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJuYW1lIjoibGVvbiIsImlhdCI6MTc0ODA3NDc3MSwiZXhwIjoxNzQ4MDc4MzcxfQ.TfuogRoC7g-LFBNwuxBxiaPAsAp9RXzgrpxspl8vDbw

{
  "name": "Test2",
  "title": "Testing Kedua",
  "isi_notes": "Ini adalah catatan untuk belajar cloud computing."
}

### Edit Note by ID (ganti :id dengan ID note sebenarnya) - Butuh Token
PUT http://localhost:5000/users/:id
Content-Type: application/json
Authorization: Bearer ACCESS_TOKEN_VALUE

{
  "name": "Belajar Cloud Computing",
  "title": "Catatan Update",
  "isi_notes": "Catatan sudah diperbarui."
}

### Delete Note by ID (ganti :id dengan ID note sebenarnya) - Butuh Token
DELETE http://localhost:5000/users/:id
Authorization: Bearer ACCESS_TOKEN_VALUE
